Repository CS2103-AY1819S1-W17-3/main, pull requests merged in 2018-10, with the labels that each got.

#75 Added UniqueGroupList class
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/main/java/seedu/address/model/group/exceptions/DuplicateGroupException.java
  src/main/java/seedu/address/model/group/exceptions/GroupNotFoundException.java
  src/test/java/seedu/address/model/group/GroupTest.java
  src/test/java/seedu/address/model/group/UniqueGroupListTest.java
  src/test/java/seedu/address/testutil/TypicalGroups.java
Labels: type.Enhancement

#79 Added support for Group functionality in Person & AddressBook class
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/group/GroupTest.java
  src/test/java/seedu/address/model/group/UniqueGroupListTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: status.Ongoing, type.Epic

#82 Update variable name and javaDoc
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/group/Date.java
  src/main/java/seedu/address/model/group/Description.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/Meeting.java
  src/main/java/seedu/address/model/group/Place.java
  src/main/java/seedu/address/model/group/Title.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/main/java/seedu/address/model/group/exceptions/DuplicateGroupException.java
  src/main/java/seedu/address/model/group/exceptions/GroupNotFoundException.java
Labels: severity.Low, status.Completed

#71 Implement FilePath command
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/model/UserPrefsChangeEvent.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/FilepathCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilepathCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/UserPrefsStorage.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FilepathCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java
Labels: status.Completed

#86 Find command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/util/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/util/PersonPropertyComparator.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonPropertyComparatorTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.High

#93 Update addGroup, removeGroup methods
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/group/GroupTest.java
  src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: type.Enhancement

#102 Add class to convert meetings to XML
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/group/EnhancedMonth.java
  src/main/java/seedu/address/model/group/TimeStamp.java
  src/main/java/seedu/address/storage/XmlAdaptedMeeting.java
  src/test/java/seedu/address/storage/XmlAdaptedMeetingTest.java
Labels: priority.High, severity.High

#110 Added updatePerson & updateGroup methods
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/group/GroupTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High, status.Ongoing, type.Enhancement

#116 Added addGroup & deleteGroup command
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteGroupCommandTest.java
  src/test/java/seedu/address/testutil/TypicalGroups.java
Labels: priority.High

#126 Added JoinCommand and LeaveCommand
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/JoinCommand.java
  src/main/java/seedu/address/logic/commands/LeaveCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/JoinCommandParser.java
  src/main/java/seedu/address/logic/parser/LeaveCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/JoinCommandTest.java
  src/test/java/seedu/address/logic/commands/LeaveCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/JoinCommandParserTest.java
  src/test/java/seedu/address/logic/parser/LeaveCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/group/UniqueGroupListTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/GroupUtil.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High, status.Completed, type.Epic

#128 Import and Export of Group and Meeting to XML
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/storage/XmlAdaptedGroup.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/test/java/seedu/address/storage/XmlAdaptedGroupTest.java
Labels: priority.High

#135 Update User guide, Developer guide; Improved on JavaDoc and some test cases
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/group/Date.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/Place.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/test/java/seedu/address/model/group/GroupTest.java
  src/test/java/seedu/address/model/group/PlaceTest.java
  src/test/java/seedu/address/model/group/UniqueGroupListTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: type.Task

#138 Add labels above lists
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InformationDisplay.fxml
Labels: type.Enhancement

#136 Refactor meet and cancel command
  src/main/java/seedu/address/logic/commands/CancelCommand.java
  src/main/java/seedu/address/logic/commands/MeetCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/main/java/seedu/address/model/group/exceptions/GroupHasNoMeetingException.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
  src/test/java/seedu/address/logic/commands/LeaveCommandTest.java
  src/test/java/seedu/address/logic/commands/MeetCommandTest.java
  src/test/java/seedu/address/logic/commands/ModelStubWithSingleGroup.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: severity.Medium, type.Bug

#142 Fix for UI not updating after MeetCommand change
  src/main/java/seedu/address/model/AddressBook.java
Labels: severity.High

#141 Changes to Documentations
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/templates/_header.html.slim
Labels: status.Ongoing

#143 Update developer guide
  docs/DeveloperGuide.adoc
  docs/images/AddGroupCommand.png
  docs/images/DeleteGroupCommand.png
  docs/images/JoinCommand.png
  docs/images/LeaveCommand.png
  docs/images/addressbookObject.png
Labels: type.Task
